#!/bin/bash

cd
mkdir -p .local/bin

# Install the workspace
jupyter lab workspace list
jupyter lab workspace import --name=abinitio workspace-gp.json
jupyter lab workspace list

# Build and install ALAMODE
git clone http://github.com/ttadano/alamode.git
cd alamode
mkdir build && cd build && cmake -DUSE_MKL_FFT=no -DSPGLIB_ROOT=$CONDA_DEFAULT_ENV .. 
make alm 
make anphon 
cd tools && make 
# Install alamode
cd ~/alamode/build
cp alm/alm anphon/anphon tools/{analyze_phonons,qe2alm,dfc2,fc_virtual} ~/.local/bin/
cd ~/alamode
cp tools/*.py ~/.local/bin/
chmod a+x ~/.local/bin/*.py

cd
id > log
set >> log
ls -laR  >> log
conda env list >> log
