#!/bin/bash

ABINIT_PP_PATH="/usr/share/abinit/psp:/usr/share/abinit/psp/HGH:/home/jovyan/abinitio-methods/psp"
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/GGA_FHI
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/GGA_HGHK
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/GGA_PAW
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/LDA_FHI
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/LDA_HGH
ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/LDA_PAW

export ABINIT_PP_PATH=${ABINIT_PP_PATH}:/srv/conda/envs/notebook/share/abinit/LDA_TM

exec "$@"